DROP DATABASE IF EXISTS BOOK;
CREATE DATABASE BOOK;
USE BOOK;

CREATE TABLE BOOK(
	id INT AUTO_INCREMENT PRIMARY KEY,
	title NVARCHAR(255),
	author NVARCHAR(255),
	price DECIMAL(10,2),
	publicationDate DATE
);

SELECT * 
FROM BOOK;

SELECT title, author
FROM BOOK
WHERE price > 50;
